### ISSUE TITLE
Prevents upgrading to bonsoir ^3.0.0

### ISSUE THREAD

**Issue by szekelyisz** [Piero512/bonsoir_linux_dbus#11]
Trying to depend on `bonsoir: ^3.0.0` fails dependency resolution with the following error:

> Because no versions of bonsoir_linux_dbus match >0.2.0 <0.3.0 and bonsoir_linux_dbus 0.2.0 depends on bonsoir_platform_interface ^2.0.0, bonsoir_linux_dbus ^0.2.0 requires bonsoir_platform_interface ^2.0.0.
> And because bonsoir >=3.0.0 depends on bonsoir_platform_interface ^3.0.0, bonsoir_linux_dbus ^0.2.0 is incompatible with bonsoir >=3.0.0.
> So, because mypackage depends on both bonsoir ^3.0.0 and bonsoir_linux_dbus ^0.2.0, version solving failed.

**Comment by Piero512** [comment]
So the platform interface was upgraded again? 🤔 Is it a breaking change? Haven't had too much free time out to check. No notification at all. Hopefully this time is not completely changed again.
