### ISSUE TITLE
Undefined name 'BonsoirLinuxDBus'

### ISSUE THREAD

**Issue by LewisHolliday** [Piero512/bonsoir_linux_dbus#7]
I get an error when building on Linux:

```
Launching lib/main.dart on Linux in debug mode...
lib/main.dart:1
ERROR: .dart_tool/flutter_build/generated_main.dart:24:9: Error: Undefined name 'BonsoirLinuxDBus'.
.dart_tool/flutter_build/generated_main.dart:24
ERROR:         BonsoirLinuxDBus.registerWith();
ERROR:         ^^^^^^^^^^^^^^^^

Exception: Build process failed
Exited (sigterm)
```

I can't seem to find BonsoirLinuxDBus within the package.

**Comment by Piero512** [comment]
Oh my, I forgot the Flutter tool depends on the package name. I only really ran the package tests. If you can't wait for a new release, you just need to edit the pubspec.yaml file with the new class name.
